// microbit_full.js (MakeCode JavaScript)
// Dynamic UI over BLE UART (RemoteXY-style):
// Web Runtime -> micro:bit:  GETCFG
// micro:bit -> Web Runtime:  CFGBEGIN <len>  + <raw JSON> + CFGEND
// Web Runtime -> micro:bit:  SET <id> <value>
// micro:bit -> Web Runtime:  UPD <id> <value>

bluetooth.startUartService()
basic.showIcon(IconNames.Heart)

// ---- UI CONFIG (generated by Builder) ----
const UI_CFG_LINES: string[] = [
'{"v":1,"title":"micro:bit Controller","grid":{"w":12,"h":8},"widgets":[',
'{"id":"btn1","t":"btn","w":4,"h":2,"label":"Button","x":0,"y":0},',
'{"id":"tgl1","t":"tgl","w":4,"h":2,"label":"Toggle","value":0,"x":4,"y":0},',
'{"id":"sld1","t":"sld","w":12,"h":2,"label":"Slider","min":0,"max":100,"step":1,"value":50,"x":0,"y":2},',
'{"id":"g1","t":"g","w":9,"h":2,"label":"Temp Gauge","min":0,"max":100,"value":0,"x":0,"y":4},',
'{"id":"lvl1","t":"lvl","w":3,"h":4,"label":"Light","min":0,"max":255,"value":0,"x":9,"y":4},',
'{"id":"txt1","t":"txt","w":12,"h":2,"label":"Status","value":"Hello","x":0,"y":6},',
'{"id":"joy1","t":"joy","w":6,"h":6,"label":"Joystick","deadzone":5,"x":6,"y":0},',
'{"id":"led1","t":"led","w":6,"h":6,"label":"LED 5x5","bits":"0000000000000000000000000","x":0,"y":0},',
'{"id":"snd1","t":"snd","w":6,"h":3,"label":"Sound","freq":440,"ms":150,"x":6,"y":6}',
']}'  // end JSON
]
const UI_CFG_JSON = UI_CFG_LINES.join("")

let sendingCfg = false

function sendLine(s: string) {
    bluetooth.uartWriteLine(s)
}

// Send UI config to runtime (framed JSON)
function sendConfig() {
    sendingCfg = true
    sendLine("CFGBEGIN " + UI_CFG_JSON.length)
    bluetooth.uartWriteString(UI_CFG_JSON)
    sendLine("")         // ensure newline after writeString
    sendLine("CFGEND")
    sendingCfg = false
}

// Send update to UI
function upd(id: string, value: any) {
    if (sendingCfg) return
    sendLine("UPD " + id + " " + value)
}

// ---- State ----
let toggleState = 0
let sliderValue = 50
let joyX = 0
let joyY = 0

let ledBits = "0000000000000000000000000" // 25 chars
function drawLedBits(bits: string) {
    // bits are row-major 5x5: index = y*5 + x
    ledBits = bits
    led.enable(true)
    basic.clearScreen()
    for (let y = 0; y < 5; y++) {
        for (let x = 0; x < 5; x++) {
            const i = y * 5 + x
            if (bits.charAt(i) == "1") led.plot(x, y)
            else led.unplot(x, y)
        }
    }
}

// ---- Incoming SET handler ----
function handleSet(id: string, valueStr: string) {

    if (id == "btn1") {
        const v = parseInt(valueStr)
        if (v == 1) {
            basic.showIcon(IconNames.Happy)
            upd("txt1", "Button pressed")
        } else {
            basic.clearScreen()
            upd("txt1", "Button released")
        }
        upd("btn1", v)
        return
    }

    if (id == "tgl1") {
        toggleState = parseInt(valueStr) ? 1 : 0
        if (toggleState) led.plot(2, 2)
        else led.unplot(2, 2)
        upd("tgl1", toggleState)
        upd("txt1", toggleState ? "Toggle ON" : "Toggle OFF")
        return
    }

    if (id == "sld1") {
        sliderValue = parseInt(valueStr)
        if (sliderValue < 0) sliderValue = 0
        if (sliderValue > 100) sliderValue = 100
        const br = Math.idiv(sliderValue * 255, 100)
        led.plotBrightness(0, 0, br)
        upd("sld1", sliderValue)
        return
    }

    if (id == "joy1") {
        // value like "x,y" where x,y are -100..100
        const comma = valueStr.indexOf(",")
        if (comma >= 0) {
            joyX = parseInt(valueStr.substr(0, comma))
            joyY = parseInt(valueStr.substr(comma + 1))
        } else {
            joyX = 0; joyY = 0
        }
        // Example: show direction on LEDs
        if (joyX == 0 && joyY == 0) {
            // do nothing
        } else {
            // map to center +/- one step
            let px = 2 + Math.idiv(joyX, 50)
            let py = 2 - Math.idiv(joyY, 50)
            if (px < 0) px = 0
            if (px > 4) px = 4
            if (py < 0) py = 0
            if (py > 4) py = 4
            basic.clearScreen()
            led.plot(px, py)
        }
        return
    }

    if (id == "led1") {
        // 25-bit string
        if (valueStr.length >= 25) {
            drawLedBits(valueStr.substr(0, 25))
            upd("led1", valueStr.substr(0, 25))
        }
        return
    }

    if (id == "snd1") {
        // "freq,ms"
        const comma = valueStr.indexOf(",")
        let f = 440
        let ms = 150
        if (comma >= 0) {
            f = parseInt(valueStr.substr(0, comma))
            ms = parseInt(valueStr.substr(comma + 1))
        }
        if (f < 50) f = 50
        if (f > 5000) f = 5000
        if (ms < 20) ms = 20
        if (ms > 2000) ms = 2000
        music.playTone(f, ms)
        upd("snd1", f + "," + ms)
        return
    }
}

// UART receive loop
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.NewLine), function () {
    let line = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine))
    // normalize CR
    if (line.length > 0 && line.charAt(line.length - 1) == "\r") {
        line = line.substr(0, line.length - 1)
    }
    if (line.length == 0) return

    if (line == "GETCFG") {
        sendConfig()
        return
    }

    if (line.substr(0, 4) == "SET ") {
        const parts = line.split(" ")
        if (parts.length >= 3) {
            const id = parts[1]
            const v = parts.slice(2).join(" ")
            handleSet(id, v)
        }
        return
    }
})

// Telemetry loop (updates g1, lvl1, txt1)
basic.forever(function () {
    const t = input.temperature()
    let mapped = t * 3
    if (mapped < 0) mapped = 0
    if (mapped > 100) mapped = 100
    const light = input.lightLevel()

    upd("g1", mapped)
    upd("lvl1", light)
    upd("txt1", "T=" + t + "C L=" + light + " Joy=" + joyX + "," + joyY)

    basic.pause(500)
})
